services:
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - db
            - redis
    db:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_DATABASE: '${DB_DATABASE:-kcal}'
            MARIADB_PASSWORD: '${DB_PASSWORD:-kcal}'
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD:-kcal}'
            MARIADB_USER: '${DB_USERNAME:-kcal}'
        volumes:
            - 'db-data:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    elasticsearch:
        image: 'elasticsearch:7.17.17'
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        deploy:
          resources:
            limits:
              memory: 1G
        volumes:
            - 'elasticsearch-data:/usr/share/elasticsearch/data'
        ports:
            - '${ELASTIC_PORT:-9200}:9200'
            - '${ELASTIC_BIN_PORT:-9300}:9300'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-kcal}'
        networks:
            - sail
        depends_on:
            - db
networks:
    sail:
        driver: bridge
volumes:
    db-data:
        driver: local
    redis-data:
        driver: local
    elasticsearch-data:
